version: "1.0"

stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    type: "git-clone"
    title: "Cloning repository"
    description: "Cloning main repository..."
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: "clone"

  prepare:
    title: Prepare Dependencies
    stage: build
    image: 'kubevious/node-builder:12'
    working_directory: "${{clone}}"
    commands:
      - npm install
      - npm install --only=dev

  run_unit_test:
    title: Run Unit Tests
    stage: test
    image: 'kubevious/node-builder:12'
    working_directory: ${{clone}}
    environment:
      - "MYSQL_HOST=mysql"
      - "MYSQL_PORT=3306"
      - "MYSQL_DB=sample-db"
      - "MYSQL_USER=root"
      - "MYSQL_PASS="
    commands:
      - npm test
    services:
      composition:
        mysql:
          image: mysql:8.0.19
          ports:
            - 3306
          environment:
            - "MYSQL_DATABASE=sample-db"
            - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
          volumes:
            - /codefresh/volume/runtime-data:/var/lib/mysql:rw
            - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
          command: "--default-authentication-plugin=mysql_native_password"
      readiness:
        image: mysql:8.0.19
        timeoutSeconds: 90
        commands:
          - "mysql --host=mysql --user=root --password= sample-db -e \"show databases;\""    